# Deep Learning & Applied AI

# Tutorial 2: Tensor operations

In this tutorial, we will cover:

- Tensor operations: broadcasting, (not)-elementwise operations, tensor contraction, einsum

Our info:

- Based on original material by Dr. Antonio Norelli (norelli@di.uniroma1.it)

Course:

- Website and notebooks will be available at https://erodola.github.io/DLAI-s2-2025/



## Introduction

In this tutorial we will continue to learn basic tensor usage, we will cover  broadcasting, fundamental linear algebra operations, and finally `einsum`, a single operation implementing the Einstein notation to rule them all!

All these tensor operations will come in handy to build our deep neural networks.
Yet, the high level API offered by PyTorch to perform GPU-acccelerated linear algebra operations may turn useful in many other fields, from microbiology to fluid dynamics.

The GPU computing paradigm offers several benefits over single-core machines or traditional supercomputers equipped with many single-core nodes.
Deep learning frameworks such as the one we are studying are a very good compromise between simplicity and expressivenes to unleash the power of GPU-computing.

To get even more control you can tackle directly the CUDA language, but we won't go there with this course!

## PyTorch

**Reminder:** Familiarize with the [PyTorch Documentation](https://pytorch.org/docs/stable/) as it will greatly assist you.






In [3]:
import torch
import numpy as np

In [4]:
# Utility print function

from typing import Union

def print_arr(*arr: Union[torch.Tensor, np.ndarray], prefix: str = "") -> None:
    """Pretty print tensors, together with their shape and type

    :param arr: one or more tensors
    :param prefix: prefix to use when printing the tensors
    """
    print(
        "\n\n".join(
            f"{prefix}{str(x)} <shape: {x.shape}> <dtype: {x.dtype}>" for x in arr
        )
    )

####Set torch and numpy random seeds for reproducibility

As we will see, several operations in deep learning (e.g. training a network) rely on randomness in order to work effectively. This means that we will get different results each time we run a test, which can make design and debugging difficult.

To this end, we usually **set a fixed seed** for the pseudo-random number generator, so that we are sure to always see the "same randomness" that makes our tests reproducible.

> Once your model works, remember to test multiple times _without_ a fixed seed! The results you got at design time may be due to overfitting the seed (e.g. you have chosen hyperparameters that happen to work particularly well with a given seed.), or just out of luck.

If you are going to use a gpu, two further options must be set.

In [5]:
import random

np.random.seed(42)
random.seed(0)

torch.manual_seed(0)
torch.cuda.manual_seed_all(0)
torch.backends.cudnn.deterministic = True  # Note that this Deterministic mode can have a performance impact
torch.backends.cudnn.benchmark = False

# We will see frameworks that aid the reproducibility of your code,
# e.g. PyTorch Lightning exposes a `seed_everything` function by default:
# https://github.com/PyTorchLightning/pytorch-lightning/blob/e1f5eacab98670bc1de72c88657404a15aadd527/pytorch_lightning/utilities/seed.py#L29

### **Tensor operations**



In [4]:
t = torch.rand(3,3)
t

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556]])

Functions that operate on tensors are often accessible in different ways:

- From the **`torch` module**...:

In [5]:
torch.add(t, t)

tensor([[0.9925, 1.5364, 0.1770],
        [0.2641, 0.6148, 1.2682],
        [0.9802, 1.7929, 0.9113]])

- ...or by tensors **methods**:

In [6]:
t.add(t)

tensor([[0.9925, 1.5364, 0.1770],
        [0.2641, 0.6148, 1.2682],
        [0.9802, 1.7929, 0.9113]])

- ...or even through **overloaded** operators:




In [7]:
t + t

tensor([[0.9925, 1.5364, 0.1770],
        [0.2641, 0.6148, 1.2682],
        [0.9802, 1.7929, 0.9113]])

None of the above operates in-place:

In [8]:
# t is unchanged
t

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556]])

These functions are all equivalent, they are *aliases* of the same method.
Personal preference, code consistency, and readability should guide your decision of which one to use.

> e.g. `torch.add(...)` may be too verbose, but in some cases it may be preferable since it makes explicit to the code-reader that you are dealing with tensors. Nevertheless, if you are using [types](https://docs.python.org/3/library/typing.html) -- and you should be using types -- it will be rarely necessary.


Most operation in PyTorch are **not in-place**. It means that the resulting tensor is a *new* tensor, and it does not share the underlying data with other tensors. Changes to the new tensor are not reflected to other tensors.
We will see in future tutorials why this is important, for now a TLDR is: **in-place operations may break the auto-differentiation mechanism**.


In-place operations are still available in PyTorch, and in some cases (e.g. when you don't need autodiff) they can be useful; they are more efficient, since they never require to perform deep copies of the data.
They are normally recognized by a trailing `_`:

In [9]:
t

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556]])

In [10]:
t.add_(t)  # notice the trailing _

tensor([[0.9925, 1.5364, 0.1770],
        [0.2641, 0.6148, 1.2682],
        [0.9802, 1.7929, 0.9113]])

In [11]:
t  # t itself changed!

tensor([[0.9925, 1.5364, 0.1770],
        [0.2641, 0.6148, 1.2682],
        [0.9802, 1.7929, 0.9113]])

Another common in-place operation is the assignment:

In [12]:
t[0] = 42
t

tensor([[42.0000, 42.0000, 42.0000],
        [ 0.2641,  0.6148,  1.2682],
        [ 0.9802,  1.7929,  0.9113]])

#### **Basic operations and broadcasting**

Basic mathematical operations $(+, -, *, /, **)$ are applied **element-wise**: for example, if `x` and `y` are two tensors, the product `x*y` is a tensor with the same size, and its values are the element-wise products of the two tensors. In mathematics, this is also called a Hadamard product.

**Broadcasting** is another powerful mechanism that allows PyTorch to perform operations on tensors of different shapes. The most basic example is summing a scalar (a rank-0 tensor) to a matrix (a rank-2 tensor).

In [13]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float64)

print(x + y)  # element-wise sum
print(x + 4.2)  # broadcasting

tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)
tensor([[5.2000, 6.2000],
        [7.2000, 8.2000]], dtype=torch.float64)


In [14]:
# other examples
print(x * y - 5)
print((x - y) / y)  # element-wise division!

tensor([[ 0.,  7.],
        [16., 27.]], dtype=torch.float64)
tensor([[-0.8000, -0.6667],
        [-0.5714, -0.5000]], dtype=torch.float64)


Broadcasting is quite powerful! When you perform an operation between two tensors with different shape, PyTorch automatically "broadcasts" the smaller tensor across the larger tensor so that they have compatible shapes.

In the example below, the sequence `v` is replicated (_without actually copying data!_) along the missing dimension so that it fits the shape of matrix `m`:

In [15]:
m = torch.arange(12).reshape(4, 3)
v = torch.tensor([100, 0, 200])
n = m + v
print_arr(m, v, n)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>

tensor([100,   0, 200]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor([[100,   1, 202],
        [103,   4, 205],
        [106,   7, 208],
        [109,  10, 211]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>


In this other example `m` and `u` are both rank-2, but the smaller one (`u`) is expanded along the dimension where it has size 1 to fit `m`:

In [16]:
m = torch.arange(12).reshape(4, 3)
u = torch.tensor([0, 10, 0, 20]).reshape(4,1)
n = m + u
print_arr(m, u, n)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>

tensor([[ 0],
        [10],
        [ 0],
        [20]]) <shape: torch.Size([4, 1])> <dtype: torch.int64>

tensor([[ 0,  1,  2],
        [13, 14, 15],
        [ 6,  7,  8],
        [29, 30, 31]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>


In the following example, both tensors are expanded along their size-1 dimensions, so that the sum makes sense:

In [17]:
w = u + v
print_arr(u, v, w)

tensor([[ 0],
        [10],
        [ 0],
        [20]]) <shape: torch.Size([4, 1])> <dtype: torch.int64>

tensor([100,   0, 200]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor([[100,   0, 200],
        [110,  10, 210],
        [100,   0, 200],
        [120,  20, 220]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>


Mastering broadcasting is hard!

However, it is very convenient as it allows writing **vectorized** code, i.e., code that avoids explicit python loops which can not be efficiently parallelized.

Technically, broadcasting takes advantage of the underlying C implementation of PyTorch and Numpy (on CPU) or CUDA implementation of Pytorch (on GPU). Here's a take-home illustration for your convenience:

![broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

##### **EXERCISE**
>
> Given two vectors $x \in \mathbb{R}^n$ and $y \in \mathbb{R}^m$, compute the differences between all possible pairs of their elements, and organize these differences in a matrix $Z \in \mathbb{R}^{n \times m}$:
> $$ z_{ij} = x_i - y_j $$

In [18]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5])

# ✏️ your code here

x_t = x.unsqueeze(-1)
d = x_t - y
print_arr(x_t, y, d)

tensor([[1],
        [2],
        [3]]) <shape: torch.Size([3, 1])> <dtype: torch.int64>

tensor([4, 5]) <shape: torch.Size([2])> <dtype: torch.int64>

tensor([[-3, -4],
        [-2, -3],
        [-1, -2]]) <shape: torch.Size([3, 2])> <dtype: torch.int64>


In [41]:
# @title 👀 Solution


out = x.unsqueeze(1) - y

# equivalent to:
# x.reshape([-1, 1]) - y

# equivalent to:
# x[:, None] - y

# equivalent to:
# x[:, None] - y[None, :]

print_arr(x, y, out)

RuntimeError: The size of tensor a (200) must match the size of tensor b (2) at non-singleton dimension 2

#### 📖 **Broadcasting, let's take a peek under the hood**

To recap: if a PyTorch operation supports broadcast, then **its tensor arguments can be implicitly expanded to be of equal sizes** (without making copies of the data).

###### **Broadcastable tensors**

Two tensors are "broadcastable" if:
- Each tensor has at least one dimension
- When iterating over the dimension sizes, starting at the trailing dimension, the dimension **sizes** must either **be equal**, **one of them is 1**, or **one of them does not exist**.


###### **Broadcasting rules**

Broadcasting two tensors together follows these rules:

1. If the input tensors have different ranks, **singleton dimensions are prepended to the shape** of the smaller one until it has the same rank as the other
2. The size in each dimension of the **output shape** is the maximum size in that dimension between the two tensors
3. An input can be used in the computation if its size in a particular **dimension either matches** the output size in that dimension, **or is a singleton dimension**
4. If an input has a dimension size of 1 in its shape, the **first data entry in that dimension will be used for all calculations** along that dimension.

**Example**:

- `m` has shape `[4, 3]`
- `v` has shape `[3,]`.


In [29]:
print_arr(m, v)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>

tensor([100,   0, 200]) <shape: torch.Size([3])> <dtype: torch.int64>


In [30]:
n = m + v
print_arr(n)

tensor([[100,   1, 202],
        [103,   4, 205],
        [106,   7, 208],
        [109,  10, 211]]) <shape: torch.Size([4, 3])> <dtype: torch.int64>



Following the Broadcasting logic, this is what happened:

- `v` has less dims than `m` so a dimension of `1` is **prepended** $\to$ `v` is now `[1, 3]`.
- Output shape will be `[max(1, 4), max(3, 3)] = [4, 3]`.
- `dim 1` of `v` matches exactly `3`; `dim 0` is `1`, so we can use the first data entry in that dimension (i.e. the whole `row 0` of `v`) each time any row is accessed. This is effectively like converting `v` from `[1, 3]` to `[4, 3]` by stacking the repeated row four times.


For more on broadcasting, see the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Functions that support broadcasting are known as universal functions (i.e. ufuncs). For Numpy you can find the list of all universal functions in the [documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

#### **EXERCISE**
>
> Given a tensor $Y \in \mathbb{R}^{n \times m}$ and an index pair $(a,b)$, for each element of $Y$ compute its $L_p$ distance to $(a,b)$, and store the resulting distance value in the corresponding cell of $Y$.
>
> In brief, compute:
> $$ y_{ij} = d_{L_p}\left( (i,j), (a,b) \right) \text{ for all }  i,j$$
>
> and visualize the resulting $Y$.
>
> Try different values of $p>0$ to see what happens.
>
> ---
>
> The [$L_p$ distance](https://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions) between two points $x$ and $y$ can be computed as: $d_{L_p}(x, y)=\left( \sum_{i=1}^n|x_i - y_i|^p\right)^{1/p}$
>
> Example: The $L_1$ distance between $(i,j) = (3, 5)$ and $(a,b) = (14, 20)$ is:
> $$ y_{3,5} = d_{L_1}( (3, 5), (14, 20) ) = |3 - 14| + |5 - 20| $$

In [42]:
# @title Utility function, you can execute and safely ignore this cell

import plotly.express as px

def plot_row_images(images: Union[torch.Tensor, np.ndarray]) -> None:
  """ Plots the images in a subplot with multiple rows.

  Handles correctly grayscale images.

  :param images: tensor with shape [number of images, width, height, <colors>]
  """
  from plotly.subplots import make_subplots
  import plotly.graph_objects as go
  fig = make_subplots(rows=1, cols=images.shape[0] ,
                      specs=[[{}] * images.shape[0]])

  # Convert grayscale image to something that go.Image likes
  if images.dim() == 3:
    images = torch.stack((images, images, images), dim= -1)
  elif (images.dim() == 4 and images.shape[-1] == 1):
    images = torch.cat((images, images, images), dim= -1)

  assert images.shape[-1] == 3 or images.shape[-1] == 4

  for i in range(images.shape[0]):
    i_image = np.asarray(images[i, ...])

    fig.add_trace(
        go.Image(z = i_image, zmin=[0, 0, 0, 0], zmax=[1, 1, 1, 1]),
        row=1, col=i + 1
    )

  fig.show()


# When using plotly pay attention that it often does not like PyTorch Tensors
# ...and it does not give any error, just a empty plot.

In [39]:
x = torch.zeros(300, 300)
a = 150
b = 150

x[a, b] = 1  # this will be overwritten by your distance-calculating code
plot_row_images(x[None, :])

In [48]:
# ✏️ your code here
p= 8
Y = (torch.abs((torch.arange(x.shape[0]).unsqueeze(-1) - a))**p + torch.abs((torch.arange(x.shape[1]).unsqueeze(0) - b))**p)**(1/p)
px.imshow(Y)

In [38]:
# @title 👀 Solution


rows = torch.arange(x.shape[0])
cols = torch.arange(x.shape[1])

# Manual computation of L1
y = (torch.abs(rows - a)[:, None] + torch.abs(cols - b)[None, :])
px.imshow(y).show()

In [41]:
# @title 👀 Solution


# Parametric computation of Lp
p = 8
y = ((torch.abs(rows - a ) ** p )[:, None] +
     (torch.abs(cols - b) ** p)[None, :]) ** (1/p)
px.imshow(y).show()

Try Solution 2 with `p=10`. What happens, and why?

In [ ]:
# @title 👀 Solution


# This works even with p=10. Why?
p = 10
y = ((torch.abs(rows.double() - a ) ** p )[:, None] +
     (torch.abs(cols.double() - b) ** p)[None, :]) ** (1/p)
px.imshow(y).show()

# -> Write your own explanation here
p = 10
print(torch.tensor(10, dtype=torch.int) ** p)
print(torch.tensor(10, dtype=torch.double) ** p)

#### **Non-elementwise operations**


PyTorch and NumPy provide many useful functions to perform computations on tensors:

In [49]:
x = torch.tensor([[1, 2, 3], [3, 4, 5]], dtype=torch.float32)
print_arr(x)

tensor([[1., 2., 3.],
        [3., 4., 5.]]) <shape: torch.Size([2, 3])> <dtype: torch.float32>


In [50]:
# Sum up all the elements
print_arr(torch.sum(x))

tensor(18.) <shape: torch.Size([])> <dtype: torch.float32>


In [51]:
# Compute the mean of each column
print_arr(torch.mean(x, dim=0))

tensor([2., 3., 4.]) <shape: torch.Size([3])> <dtype: torch.float32>


> **REMEMBER!**
>
> In order to avoid confusion with the `dim` parameter, you can think of it as an **index over the list returned by `tensor.shape`**. The operation is performed by iterating over that dimension.
>
> Example above: since our tensor `x` has shape `[2, 3]`, the dimension `dim=0` operates along the `2`.
>
> Visually (here array means _tensor_):
>
><img src="https://qph.fs.quoracdn.net/main-qimg-30be20ab9458b5865b526d287b4fef9a" width="500" >

In [53]:
print_arr(x)

tensor([[1., 2., 3.],
        [3., 4., 5.]]) <shape: torch.Size([2, 3])> <dtype: torch.float32>


In [54]:
# Compute the product of each row
print_arr(torch.prod(x, dim=1))

tensor([ 6., 60.]) <shape: torch.Size([2])> <dtype: torch.float32>


In [55]:
# Max along the rows (i.e. max value in each column)
values, indices = torch.max(x, dim=0)
print_arr(values)

tensor([3., 4., 5.]) <shape: torch.Size([3])> <dtype: torch.float32>


In [56]:
# Max along the columns (i.e. max value in each row)
values, indices = torch.max(x, dim=1)
print_arr(values)

tensor([3., 5.]) <shape: torch.Size([2])> <dtype: torch.float32>


##### 📖 **Dim parameter, let's take a peek under the hood**


Let's see what the `dim` parameter exactly does:

In [59]:
dim = 2

a = torch.arange(2*3*4).reshape(2, 3, 4)
out = a.sum(dim=dim)
out

tensor([[ 6, 22, 38],
        [54, 70, 86]])

In [60]:
# It is summing over the `dim` dimension, i.e.:
a.shape

torch.Size([2, 3, 4])

In [61]:
# The `dim` dimension has 4 elements
a.shape[dim]

4

In [62]:
# The dimension dim collapses, the output tensor will have shape:
new_shape = a.shape[:dim] + a.shape[dim + 1:]
new_shape

torch.Size([2, 3])

In [63]:
# Explicitly compute the sum over dim
out = torch.zeros(new_shape)

# iterate over all the rows
for r in range(a.shape[0]):
  # iterate over all the columns in the r-th row
  for c in range(a.shape[1]):

    for i in range(a.shape[dim]): # <- sum over 'dim'

      out[r, c] += a[r, c, i]

out

# **DO NOT** use for loops in your code

tensor([[ 6., 22., 38.],
        [54., 70., 86.]])

###### **EXERCISE**
>
> Given a matrix $X \in R^{k \times k}$:
> - Compute the mean of the values along its diagonal.
>
> Perform this computation in at least two different ways, then check that the results are the same.

In [64]:
x = torch.rand(4, 4)
print_arr(x)

tensor([[0.6323, 0.3489, 0.4017, 0.0223],
        [0.1689, 0.2939, 0.5185, 0.6977],
        [0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194]]) <shape: torch.Size([4, 4])> <dtype: torch.float32>


In [82]:
# ✏️ your code here
mean1 = torch.mean(x[torch.arange(x.shape[0]), torch.arange(x.shape[1])])

mean2 = torch.mean(torch.diag(x))

mean1


tensor(0.4070)

In [83]:
# @title 👀 Solution


a = torch.mean(x[torch.arange(x.shape[0]), torch.arange(x.shape[1])])
b = torch.sum(torch.eye(x.shape[0]) * x) / x.shape[0]
c = torch.trace(x) / x.shape[0]
d = torch.mean(torch.diag(x))

print(torch.equal(a, b) and torch.equal(a, c) and torch.equal(a, d))
print_arr(a)

True
tensor(0.4070) <shape: torch.Size([])> <dtype: torch.float32>


##### **EXERCISE**
>
> Given a binary non-symmetric matrix $X \in \{0, 1\}^{n\times n}$, build the symmetric matrix $Y \in \{0, 1\}^{n \times n}$ defined as:
> $$
y_{ij} =
\begin{cases}
1 & \text{if } x_{ij} = 1 \\
1 & \text{if } x_{ji} = 1 \\
0 & \text{otherwise}
\end{cases}
$$
>
> *Hint*: search for `clamp` in the [docs](https://pytorch.org/docs/stable/index.html)

In [6]:
x = torch.randint(0, 2, (5, 5))  # Non-symmetric matrix
x

tensor([[0, 1, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 0, 0]])

In [9]:
# ✏️ your code here

y = torch.clamp(x, min = torch.transpose(x, 0, 1))
print_arr(y)

tensor([[0, 1, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [0, 1, 1, 0, 1],
        [1, 1, 1, 1, 0]]) <shape: torch.Size([5, 5])> <dtype: torch.int64>


In [10]:
# @title 👀 Solution


(x + x.transpose(1, 0)).clamp(max=1)

tensor([[0, 1, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [0, 1, 1, 0, 1],
        [1, 1, 1, 1, 0]])

#### **Tensor contractions**

##### **Matrix multiplication**

Given $X \in R^{n \times d}$ and $Y \in R^{d \times v}$, their matrix multiplication $Z \in R^{n \times v}$ is defined as:

$$ \sum_{k=0}^{d} x_{ik} y_{kj} = z_{ij} $$


In [11]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
y = torch.tensor([[1, 2], [2, 1]])
print_arr(x, y)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) <shape: torch.Size([3, 2])> <dtype: torch.int64>

tensor([[1, 2],
        [2, 1]]) <shape: torch.Size([2, 2])> <dtype: torch.int64>


In [12]:
# as we will see, matmul's functionality is not limited to matrix-matrix multiplication
torch.matmul(x, y)

tensor([[ 5,  4],
        [11, 10],
        [17, 16]])

In [13]:
x @ y  # Operator overload for matmul

tensor([[ 5,  4],
        [11, 10],
        [17, 16]])

In [14]:
torch.mm(x, y)  # PyTorch function, only works for rank-2 tensors (matrices) https://pytorch.org/docs/stable/generated/torch.mm.html

tensor([[ 5,  4],
        [11, 10],
        [17, 16]])

In [15]:
x.mm(y)  # Tensor method

tensor([[ 5,  4],
        [11, 10],
        [17, 16]])

In [16]:
torch.einsum('ik, kj -> ij', (x, y))  # Einsum notation!

# It summed up dimension labeled with the index `k`

tensor([[ 5,  4],
        [11, 10],
        [17, 16]])

##### **Dot product**
Also known as scalar product or inner product.
Given $x \in \mathbb{R}^k$ and $y \in \mathbb{R}^k$, the dot product $z \in \mathbb{R}$ is defined as:

$$ \sum_{i=0}^{k} x_i y_i = z $$

In [17]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print_arr(x, y)

tensor([1, 2, 3]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor([4, 5, 6]) <shape: torch.Size([3])> <dtype: torch.int64>


In [18]:
# We want to perform:
(1 * 4) + (2 * 5) + (3 * 6)

32

In [19]:
torch.dot(x, y)  # PyTorch function

tensor(32)

In [20]:
x.dot(y) # Tensor method

tensor(32)

In [21]:
x @ y  # PyTorch operator again overloading matmul

tensor(32)

In [22]:
torch.einsum('i, i ->', (x, y))  # Einstein notation!

# Read it as:
# - iterate with i along x
# - iterate with i along y
# - compute the product at each iteration
# - sum the products and return a scalar (-> means return a scalar)

# More in general, Einstein notation:
# Multiply point-wise repeated indices in the input
# Sum up along the indices that `do not` appear in the output

# More on this below!

tensor(32)

##### **Batch matrix multiplication**

Often we want to perform more operations together. Why?
- Reduce the **overhead of uploading** each tensor to/from the GPU memory
- **Better parallelization** of the computation

Given two 3D tensors, each one containing ``b`` matrices,
$X \in \mathbb{R}^{b \times n \times m}$
and  
$Y \in \mathbb{R}^{b \times m \times p}$,

We want to multiply together each $i$-th pair of matrices, obtaining a tensor $Z \in \mathbb{R}^{b \times n \times p}$ defined as:

$$ z_{bij} = \sum_{k=0}^m x_{bik} y_{bkj} $$

In [23]:
# here b = 2 matrices
x = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])  # 3x2 matrices
y = torch.tensor([[[1, 2], [2, 1]], [[1, 2], [2, 1]]])  # 2x2 matrices
print_arr(x, y)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]) <shape: torch.Size([2, 3, 2])> <dtype: torch.int64>

tensor([[[1, 2],
         [2, 1]],

        [[1, 2],
         [2, 1]]]) <shape: torch.Size([2, 2, 2])> <dtype: torch.int64>


In [24]:
torch.bmm(x, y)  # **not** torch.mm

tensor([[[ 5,  4],
         [11, 10],
         [17, 16]],

        [[ 5,  4],
         [11, 10],
         [17, 16]]])

In [25]:
# Operator overload! again, matmul is actually doing the job
x @ y

tensor([[[ 5,  4],
         [11, 10],
         [17, 16]],

        [[ 5,  4],
         [11, 10],
         [17, 16]]])

In [26]:
torch.einsum('bik, bkj -> bij', (x, y)) # Einstein notation!

tensor([[[ 5,  4],
         [11, 10],
         [17, 16]],

        [[ 5,  4],
         [11, 10],
         [17, 16]]])

##### 📖 **Broadcast matrix multiplication**

Given a matrix $Y \in \mathbb{R}^{m \times p}$ and $b$ matrices of size $n \times m$ organized in a 3D tensor $X \in \mathbb{R}^{b \times n \times m}$, we want to multiply together each matrix $X_{i,:,:}$ with $Y$, obtaining a tensor $Z \in R^{b \times n \times p}$ defined as:

$$ z_{bij} = \sum_{k=0}^m x_{bik} y_{kj} $$


In [27]:
x = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])
y = torch.tensor([[1, 2], [2, 1]])
print_arr(x, y)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]) <shape: torch.Size([2, 3, 2])> <dtype: torch.int64>

tensor([[1, 2],
        [2, 1]]) <shape: torch.Size([2, 2])> <dtype: torch.int64>


In [28]:
torch.matmul(x, y)  # always uses the last two dimensions

tensor([[[ 5,  4],
         [11, 10],
         [17, 16]],

        [[ 5,  4],
         [11, 10],
         [17, 16]]])

In [29]:
x @ y   # still using the last two dimensions since @ overloads matmul

tensor([[[ 5,  4],
         [11, 10],
         [17, 16]],

        [[ 5,  4],
         [11, 10],
         [17, 16]]])

##### **EXERCISE**
>
> Use the einsum notation to compute the equivalent broadcast matrix multiplication!

In [31]:
torch.einsum('bik, kj -> bij', (x,y))

tensor([[[ 5,  4],
         [11, 10],
         [17, 16]],

        [[ 5,  4],
         [11, 10],
         [17, 16]]])

### **Einsum notation**

Einstein notation is a way to express complex operations on tensors.

- It is **concise but expressive enough** to perform almost every operation you will need in building your neural networks, allowing you to think of the only thing that matters... **dimensions!**
- You will **not need to check your dimensions** after an einsum operation, since the dimensions themselves are *defining* the tensor operation.
- You will **not need to shape-comment** your tensors. Those comments do not work: they are bound to get outdated.
-  You will not need to explicitly code **intermediate operations** such as reshaping, transposing and intermediate tensors.
- It is **not library-specific**, being avaiable in ``numpy``, ``pytorch``, ``tensorflow`` and ``jax`` with the same signature. So you do not need to remember the functions signature in all the frameworks.
- It can sometimes be compiled to high-performing code (e.g. [Tensor Comprehensions](https://pytorch.org/blog/tensor-comprehensions/))

Check [this blog post by Olexa Bilaniuk](https://obilaniu6266h16.wordpress.com/2016/02/04/einstein-summation-in-numpy/) to take a peek under the hood of einsum and [this one by Tim Rocktäschel](https://rockt.github.io/2018/04/30/einsum) for several examples.

Its formal behavior is well described in the [Numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html).
However, it is very intuitive and better explained through examples.

![alt text](https://obilaniu6266h16.files.wordpress.com/2016/02/einsum-fmtstring.png?w=676)

> *Historical note (taken from O.Bilaniuk's post)*
>
> Einstein had no part in the development of this notation. He merely popularized it, by expressing his entire theory of General Relativity in it. In a letter to [Tullio Levi-Civita](https://en.wikipedia.org/wiki/Tullio_Levi-Civita), co-developer alongside [Gregorio Ricci-Curbastro](https://en.wikipedia.org/wiki/Gregorio_Ricci-Curbastro) of Ricci calculus (of which this summation notation was only a part), Einstein wrote:
>
> " *I admire the elegance of your method of computation; it must be nice to ride through these fields upon the horse of true mathematics while the like of us have to make our way laboriously on foot.* "

In [33]:
a = torch.arange(6).reshape(2, 3)  # will use this in the examples below

###### **Matrix transpose**

$$ B_{ji} = A_{ij} $$

In [34]:
# The characters are indices along each dimension
b = torch.einsum('ij -> ji', a)
print_arr(a, b)

tensor([[0, 1, 2],
        [3, 4, 5]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor([[0, 3],
        [1, 4],
        [2, 5]]) <shape: torch.Size([3, 2])> <dtype: torch.int64>


###### **Sum**

$$ b = \sum_i \sum_j A_{ij} := A_{ij} $$


In [35]:
# Indices that do not appear in the output tensor are summed up
b = torch.einsum('ij -> ', a)
print_arr(a, b)

tensor([[0, 1, 2],
        [3, 4, 5]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor(15) <shape: torch.Size([])> <dtype: torch.int64>


###### **Column sum**

$$ b_j = \sum_i A_{ij} := A_{ij} $$

In [36]:
# Indices that do not appear in the output tensor are summed up,
# ...even if some other index appears
b = torch.einsum('ij -> j', a)
print_arr(a, b)

tensor([[0, 1, 2],
        [3, 4, 5]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor([3, 5, 7]) <shape: torch.Size([3])> <dtype: torch.int64>


###### **EXERCISE**
>
> Given a binary tensor $X \in \{0, 1\}^{n \times m}$ return a tensor $y \in \mathbb{R}^{n}$ that has in the $i$-th position the **number of ones** in the $i$-th row of $X$.
>
>Give a solution using `einsum`, and a solution using standard manipulation.

In [39]:
x = (torch.rand(100, 200) > 0.5).int()

In [43]:
# Display a binary matrix with plotly

fig = px.imshow(x)
fig.show()

In [44]:
# ✏️ your code here

torch.einsum('ij->i', x)

tensor([104, 109,  98, 105,  98,  93,  93, 102, 102,  95, 108, 102,  98, 101,
         94, 101, 103, 103, 107, 101,  94, 108, 109,  91, 101,  88, 101, 106,
        104, 114,  96, 110, 106,  88, 105, 104, 100, 101, 105, 108, 104,  93,
        103,  99,  92,  90, 110,  96,  94, 101,  98, 100,  98, 100, 112,  93,
         98, 105, 103,  85, 100,  89,  98, 111, 108,  96,  96, 102,  89, 101,
        104, 104,  82,  95,  95,  97,  99, 105,  94,  98,  97, 107,  90,  90,
        103, 100, 100, 108, 113, 107,  93,  96, 101, 103,  97, 107,  97, 103,
        112, 101])

In [46]:
# @title 👀 Solution


# Count the number of ones in each row
row_ones = torch.einsum('ij -> i', x)

row_ones2 = torch.sum(x, dim=-1)  # recall that -1 refers to the last dimension

torch.equal(row_ones, row_ones2)

True

In [47]:
px.imshow(row_ones[:, None]).show()
print(f'Sum up the row counts: {row_ones.sum()}\nSum directly all the ones in the matrix: {x.sum()}')

Sum up the row counts: 10018
Sum directly all the ones in the matrix: 10018


###### **Matrix-vector multiplication**

$$ c_i = \sum_k A_{ik}b_k := A_{ik}b_k $$

In [48]:
# Repeated indices in different input tensors indicate pointwise multiplication
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
c = torch.einsum('ik, k -> i', [a, b])  # Multiply on k, then sum up on k
print_arr(a, b, c)

tensor([[0, 1, 2],
        [3, 4, 5]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor([0, 1, 2]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor([ 5, 14]) <shape: torch.Size([2])> <dtype: torch.int64>


###### **Matrix-matrix multiplication**

$$ C_{ij} = \sum_k A_{ik}B_{kj} := A_{ik}B_{kj} $$

📖 Understanding einsum, what happens inside?

![alt text](https://obilaniu6266h16.files.wordpress.com/2016/02/einsum-matrixmul.png?w=676)

In [49]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
c = torch.einsum('ik, kj -> ij', [a, b])
print_arr(a, b, c)

tensor([[0, 1, 2],
        [3, 4, 5]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]) <shape: torch.Size([3, 5])> <dtype: torch.int64>

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]]) <shape: torch.Size([2, 5])> <dtype: torch.int64>


###### **Dot product multiplication**

$$ c = \sum_i a_i b_i := a_i b_i $$

In [50]:
a = torch.arange(3)
b = torch.arange(3,6)
c = torch.einsum('i,i->', (a, b))
print_arr(a, b, c)

tensor([0, 1, 2]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor([3, 4, 5]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor(14) <shape: torch.Size([])> <dtype: torch.int64>


###### **Point-wise multiplication**
Also known as Hadamard product:

$$ C_{ij} = A_{ij} B_{ij} $$

In [51]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
c = torch.einsum('ij, ij -> ij', (a, b))
print_arr(a, b, c)

tensor([[0, 1, 2],
        [3, 4, 5]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor([[ 6,  7,  8],
        [ 9, 10, 11]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>

tensor([[ 0,  7, 16],
        [27, 40, 55]]) <shape: torch.Size([2, 3])> <dtype: torch.int64>


###### **Outer product**
Given two column vectors of length $m$ and $n$ respectively,
\begin{align*}
\mathbf{a}=\left[\begin{array}{c}
a_{1} &
a_{2} &
\dots &
a_{m}
\end{array}\right]^\top, \quad \mathbf{b}=\left[\begin{array}{c}
b_{1} &
b_{2} &
\dots &
b_{n}
\end{array}\right]^\top
\end{align*}
their outer product, denoted $\mathbf{a} \otimes \mathbf{b}$, is defined as the $m \times n$ matrix $\mathbf{C}$ obtained by multiplying each element of $\mathbf{a}$ by each element of $\mathbf{b}$:
\begin{align*}
\mathbf{a} \otimes \mathbf{b}=\mathbf{C}=\left[\begin{array}{cccc}
a_{1} b_{1} & a_{1} b_{2} & \ldots & a_{1} b_{n} \\
a_{2} b_{1} & a_{2} b_{2} & \ldots & a_{2} b_{n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m} b_{1} & a_{m} b_{2} & \ldots & a_{m} b_{n}
\end{array}\right]
\end{align*}
Or, in index notation,
$$ C_{ij} = a_i b_j $$

In [52]:
a = torch.arange(3)
b = torch.arange(3,7)
c = torch.einsum('i, j -> ij', (a, b))
print_arr(a, b, c)

tensor([0, 1, 2]) <shape: torch.Size([3])> <dtype: torch.int64>

tensor([3, 4, 5, 6]) <shape: torch.Size([4])> <dtype: torch.int64>

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]]) <shape: torch.Size([3, 4])> <dtype: torch.int64>


In [53]:
# Using the standard PyTorch API
torch.outer(a, b)

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [54]:
# Using broadcasting black magic
a[:, None] * b[None, :]

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

###### 📖 **Batch matrix multiplication**

$$ c_{bij} = \sum_k a_{bik} b_{bkj} $$

In [55]:
a = torch.randn(2,2,5)
b = torch.randn(2,5,3)
c = torch.einsum('bik,bkj->bij', [a, b])
print_arr(a, b, c)

tensor([[[ 0.4165,  0.4944,  0.1506,  0.5694, -0.1354],
         [-0.8608, -1.4396, -1.9325, -0.6966,  0.9595]],

        [[-1.2665, -1.2487,  0.3264, -0.3027, -0.6128],
         [ 0.1482, -0.7410, -1.5671,  0.3429, -0.0155]]]) <shape: torch.Size([2, 2, 5])> <dtype: torch.float32>

tensor([[[ 0.5019, -0.5613,  0.6088],
         [ 1.5112,  0.2794,  0.4930],
         [ 0.2541, -1.2653, -1.0475],
         [-0.2851,  0.9735, -0.4204],
         [ 1.3442, -0.6493,  0.5051]],

        [[ 1.5791,  0.3153, -0.5771],
         [ 0.0193, -1.2421, -0.0950],
         [ 1.0298,  1.8572,  1.3945],
         [ 0.9388,  1.2451,  0.3389],
         [ 0.3680, -2.2995, -2.3876]]]) <shape: torch.Size([2, 5, 3])> <dtype: torch.float32>

tensor([[[ 0.6501,  0.3560,  0.0317],
         [-1.6100,  1.2250,  1.5682]],

        [[-2.1975,  2.7902,  2.6652],
         [-1.0779, -1.4807, -2.0473]]]) <shape: torch.Size([2, 2, 3])> <dtype: torch.float32>


###### **EXERCISE**
> Implement:
> - Matrix transpose with einsum, in particular assume you have a batch of images of shape $(B, C, H, W)$ and you want to turn it into having shape $(B, H, W, C)$
> - Quadratic form with einsum  ($y = v^TMv$)

In [57]:
a = torch.randn(2,2,5,6)
print_arr(a[:4,:4])
b=torch.einsum('bchw->bhwc', a)
print_arr(b[:4,:4])


tensor([[[[ 0.2348,  1.0176,  2.3873,  0.7977, -1.1479,  0.4278],
          [ 0.9954,  0.4747,  0.6960, -0.2052, -1.0362, -0.7705],
          [-0.8111, -0.0519,  0.5394,  0.0653,  0.3215, -0.3022],
          [ 0.4497,  1.3772, -0.6697, -0.6611,  0.1589, -1.0330],
          [ 0.1081,  0.3805, -2.1267, -0.0713, -0.8282, -0.9202]],

         [[ 1.1822, -2.7577,  1.3389,  0.3762,  1.7445,  0.7219],
          [-0.1323,  0.1505,  0.5652, -0.2927,  1.8023, -2.3015],
          [ 0.2075, -2.9988, -1.7305, -0.2410,  0.3309,  0.9904],
          [-1.6862, -0.3482, -0.4026, -1.9417,  0.5287,  1.0021],
          [ 0.1976,  0.4460,  0.1022,  0.8036,  1.3096,  1.2125]]],


        [[[-0.8371,  0.1556, -0.1553, -1.3213,  0.6166, -0.6136],
          [-0.7304,  1.4987,  1.6604,  0.7991, -0.6372,  0.1574],
          [ 0.5018, -0.1909,  0.0844, -0.2144, -1.2243,  0.3744],
          [ 0.5272,  0.4563,  0.2688, -1.2791,  0.5757, -1.9152],
          [-0.1767, -0.1109, -0.8746,  0.6407, -0.3486,  0.1404]],

  

#### 📖 Singleton dimensions

 In deep learning it is very common to **add or remove dimensions of size $1$** in a tensor. As we mentioned, this is called **unsqueezing** and **squeezing**, and it occurs often during batch processing, manipulating feature maps, making network layers compatible, and in several other occasions.

 It is possible to perform these operations in different ways, feel free to use
 whatever is more comfortable to you! Again, **prefer readability to cryptic one-liners** for the sanity of a hypothetical unknown reader or your future self.

In the example below, we transform a rank-1 tensor into a rank-2 "column", and back to a rank-1:

In [ ]:
# Define a rank-1 tensor we will use
x = torch.arange(6)
print_arr(x)

Transform **`x` into a column tensor** in four different ways.

Remember that the shape of a column tensor is in the form: `(rows, 1)`

In [ ]:
# 1)
# Use the `reshape` or `view` functions

y1 = x.reshape(-1, 1)
y2 = x.view(-1, 1)

print_arr(y1, y2)

In [ ]:
# 2)
# Use the specific `unsqueeze` function to unsqueeze a dimension

y3 = x.unsqueeze(dim=-1)
y4 = x.unsqueeze(dim=1)

print_arr(y3, y4)

In [ ]:
# 3)
# Explicitly index a non-existing dimension with `None`

y5 = x[:, None]

print_arr(y5)

In [ ]:
# 4)
# Same as before, but do not assume a rank-2 tensor and index the last one.
# This approach is useful to write functions that work both for
# batched or non-batched data

y6 = x[..., None]

print_arr(y5)

In [ ]:
# Now we go back to a rank-1 tensor

x1 = y1.reshape(-1)
x2 = y2.view(-1)          # Explicity enforce to get a view of the tensors, without copying data
x3 = y3.squeeze(dim=-1)
x4 = y4.squeeze(dim=1)
x5 = y5[:, 0]             # Manually collapse the dimension with an integer indexing
x6 = y6[..., 0]

print_arr(x1, x2, x3, x4, x5, x6)

> **NOTE**
>
> indexing with `...` means  **keeping all the other dimensions the same**.
> Keep in mind that `...` is just a Python singleton object (just as `None`).
> Its type is Ellipsis:


In [ ]:
...

In [ ]:
x = torch.rand(3,3,3)
x[:, :, 0]

In [ ]:
x[..., 0]

### Tensor types
Pay attention to the tensor types!
Several methods are available to convert tensors to different types:

In [ ]:
a = torch.rand(3, 3) + 0.5

In [ ]:
a.int()

In [ ]:
a.long()

In [ ]:
a.float()

In [ ]:
a.double()

In [ ]:
a.bool()

In [ ]:
a.to(torch.double)

In [ ]:
a.to(torch.uint8)

In [ ]:
a.bool().int()

**Pro tip:** Do not try to memorize all the PyTorch API!

> Learn to understand what operation should already exist and search for it, when you need it. If it is something common, and it usually is, chances are it already exists.

Google, StackOverflow and the docs are your friends!

### 📖 Einops

If you liked the `einsum` operation, have fun with the [einops](https://github.com/arogozhnikov/einops) package! 🚀

It is a third-party library, compatible with most frameworks, that brings superpowers to `einsum`. We will not use the `einops` library in the tutorials, however, feel free to read the [docs](https://github.com/arogozhnikov/einops) and use it.

![](http://arogozhnikov.github.io/images/einops/einops_video.gif)


### Final exercises

These final exercises are designed to showcase the elegant solutions of einsum.

Feel free to also write down solutions that do _not_ use einsum, but rather with standard tensor manipulation!


#### **EXERCISE 1**
>
> You are given $b$ images with size $w \times h$. Each pixel in each image has three color channels, `(r, g, b)`. These images are organized in a tensor $X \in \mathbb{R}^{w \times b \times c \times h}$.
>
> You want to apply a linear trasformation to the color channel of each single image. In particular, you want to :
> - **Convert each image into a grey scale image**.
> - **Afterthat, transpose the images** to swap the height and width.
>
> The linear traformation that converts from `(r, g, b)` to grey scale is simply a linear combination of `r`, `g` and `b`. It can be encoded in the following 1-rank tensor $y \in \mathbb{R}^3$:

In [ ]:
y = torch.tensor([0.2989, 0.5870, 0.1140], dtype=torch.float)


> At the end, you want to obtain a tensor $Z \in \mathbb{R}^{b \times w \times h}$.
>
> Write the PyTorch code that performs this operation.

In [ ]:
# Create the input tensors for the exercise
# Execute and ignore this cell

from skimage import io
from skimage.transform import resize

size = 100

image1 = io.imread('https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/260px-Earth_Eastern_Hemisphere.jpg')
image1 = torch.from_numpy(resize(image1, (size, size), anti_aliasing=True)).float()  # Covert  to float type
image1 = image1[..., :3]  # remove alpha channel

image2 = io.imread('https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg/628px-The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg')
image2 = torch.from_numpy(resize(image2, (size, size), anti_aliasing=True)).float()
image2 = image2[..., :3]  # remove alpha channel

image3 = io.imread('https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Wikipedia-logo-v2.svg/1920px-Wikipedia-logo-v2.svg.png')
image3 = torch.from_numpy(resize(image3, (size, size), anti_aliasing=True)).float()
image3 = image3[..., :3]  # remove alpha channel

source_images = torch.stack((image1, image2, image3), dim=0)
images = torch.einsum('bwhc -> wbch', source_images)

In [ ]:
# Plot source images
plot_row_images(source_images)

In [ ]:
# ✏️ your code here

In [ ]:
# @title 👀 Solution


# Grey-fy all images together, using the `images` tensor
gray_images = torch.einsum('wbch, c -> bwh', (images, y))

# What if you want to transpose the images?
gray_images_tr = torch.einsum('wbch, c -> bhw', (images, y))

In [ ]:
# Plot the gray images
plot_row_images(gray_images)

In [ ]:
# Plot the gray transposed images
plot_row_images(gray_images_tr)

#### **EXERCISE 2**
>
> Given $k$ points organized in a tensor $X \in \mathbb{R}^{k \times 2}$ apply a reflection along the $y$ axis as a linear transformation.


In [ ]:
# Define some points in R^2
x = torch.arange(100, dtype=torch.float)
y = x ** 2

# Define some points in R^2
data = torch.stack((x, y), dim=0).t()

In [ ]:
px.scatter(x = data[:, 0].numpy(), y = data[:, 1].numpy())

In [ ]:
# ✏️ your code here

In [ ]:
# @title 👀 Solution


# Define a matrix that encodes a linear transformation
S = torch.tensor([[-1, 0],
                  [ 0, 1]], dtype=torch.float)

# Apply the linear transformation: the order is important
new_data = torch.einsum('nk, kd -> nd', (data, S))

# Double check yourself:
# The linear transformation correctly maps the basis vectors!
S @ torch.tensor([[0],
                  [1]], dtype=torch.float)
S @ torch.tensor([[1],
                  [0]], dtype=torch.float)

# Check if at least the shape is correct
new_data.shape

In [ ]:
# Plot the new points
px.scatter(x = new_data[:, 0].numpy(), y = new_data[:, 1].numpy())

#### **EXERCISE 3**
>
>  You are given $b$ images with size $w \times h$. Each pixel in each image has `(r, g, b)` channels. These images are organized in a tensor $X \in \mathbb{R}^{w \times b \times c \times h}$, i.e. the same tensor as in the exercise 1.
>
> You want to swap the `red` color with the `blue` color, and decrease the intensity of the `green` by half.
>
> Perform the transformation on all the images simultaneously.

In [ ]:
images.shape

In [ ]:
# ✏️ your code her

In [ ]:
# @title 👀 Solution


# Define the linear transformation to swap the blue and red colors
# and half the green
S = torch.tensor([[ 0, 0, 1],
                  [ 0, .5, 0],
                  [ 1, 0, 0]], dtype=torch.float)

# Apply the linear transformation to the color channel!
rb_images = torch.einsum('wbch, dc -> wbdh', (images, S))

# Let's try to read into the einsum operation above.
#
# For each pixel p=(r,g,b) in each image of the images tensor, we want to apply
# the transformation S @ p. In einsum notation, this would be a transformation
# represented as 'dc, c -> d' or equivalently 'c, dc -> d' if we swap the order
# of the two arguments.
#
# Now, our pixels are stored in a 4d tensor with dimensions wbch. All we want
# einsum to do, is loop over the dimensions w, b, and h, extract a pixel at each
# iteration, and apply the 'c, dc -> d' transformation to it.
#
# So here's how all the above would read in einsum notation:
#   'wbch, dc -> wbdh'
# Basically the w, b, h dimensions stay the same (we're just looping over them),
# while the c dimension gets transformed to d by application of S.

# Finally permute the dimensions so that we can use plot_row_images().
rb_images = rb_images.permute(1, 0, 3, 2)

In [ ]:
# @title 👀 Alternative solution


S = torch.tensor([[ 0, 0, 1],
                  [ 0, .5, 0],
                  [ 1, 0, 0]], dtype=torch.float)

# Instead of explicitly permuting the dimensions of the final result
# to make it work with plot_row_images(), we can directly ask einsum
# to apply a permutation for us!
#
# We just change the output dimensions 'wbdh' to 'bwhd':
rb_images = torch.einsum('wbch, dc -> bwhd', (images, S))

In [ ]:
plot_row_images(rb_images)

#### 📖 **EXERCISE 4**
>
>  You are given $b$ images with size $w \times h$. Each pixel in each image has `(r, g, b)` colors. These images are organized in a tensor $X \in \mathbb{R}^{w \times b \times c \times h}$, i.e. the same tensor as exercise 1 and 3.
>
> You want to **convert each image into a 3D point cloud**:
> - the `(x, y)` coordinates of each point in the point cloud are the **indices** of the pixels in the original image
> - the `z` coordinate of each point in the point cloud is the $L_2$ norm of the color of the corresponding pixel, multiplied by $10$
>
> *Hint*: you may need some other PyTorch function, search the docs!

In [ ]:
# @title 👀 Solution


# Just normalize the tensor into the common form [batch, width, height, colors]
imgs = torch.einsum('wbch -> bwhc', images)
imgs.shape

# The x, y coordinate of the point cloud are all the possible pairs of indices (i, j)
row_indices = torch.arange(imgs.shape[1], dtype=torch.float)
col_indices = torch.arange(imgs.shape[2], dtype=torch.float)
xy = torch.cartesian_prod(row_indices , col_indices)

# Compute the L2 norm for each pixel in each image
depth = imgs.norm(p=2, dim = -1)
# depth = torch.einsum('bwhc, bwhc -> bwh', (imgs, imgs)) ** (1/2)

# For every pair (i, j), retrieve the L2 norm of that pixel
z = depth[:, xy[:, 0].long(), xy[:, 1].long()] * 10

# Adjust the dimensions, repeat and concatenate accordingly
xy = xy.repeat(imgs.shape[0], 1, 1)  # x,y coordinates are constant for the three images
clouds = torch.cat((xy, z[..., None] ), dim= 2)

# Three images, 10000 points, each point with coordinates x,y,z in 3D
clouds.shape

In [ ]:
# Utility function
# Execute and ignore this cell

from typing import Union

def plot_3d_point_cloud(cloud: Union[torch.Tensor, np.ndarray]) -> None:
  """ Plot a single 3D point cloud

  :param cloud: tensor with shape [number of points, coordinates]
  """
  import pandas as pd
  df = pd.DataFrame(np.asarray(cloud), columns=['x', 'y', 'z'])
  fig = px.scatter_3d(df, x=df.x, y=df.y, z=df.z, color=df.z, opacity=1, range_z=[0, 30])
  fig.update_layout({'scene_aspectmode': 'data', 'scene_camera':  dict(
          up=dict(x=0., y=0., z=0.),
          eye=dict(x=0., y=0., z=3.)
      )})
  fig.update_traces(marker=dict(size=3,),
                    selector=dict(mode='markers'))
  _ = fig.show()

In [ ]:
plot_3d_point_cloud(clouds[0, ...])

In [ ]:
plot_3d_point_cloud(clouds[1, ...])

In [ ]:
plot_3d_point_cloud(clouds[2, ...])